apiVersion: v1
kind: Service
metadata:
  name: {{ template "httpbin.fullname" . }}
  namespace: {{.Values.namespace}}
  labels:
    app: {{ template "httpbin.name" . }}
spec:
  # type: LoadBalancer
  ports:
    - name: http
      port: {{.Values.servicePort}}
      targetPort: {{.Values.containerPort}}
  selector:
    app: {{ template "httpbin.name" . }}
